### ISSUE TITLE
17. Είμαι ο Βρασίδας θα ήθελα όταν δεν υπάρχουν διαθέσιμες φωτογραφίες από την αναζήτηση που έκανα, να με ενημερώνει ότι δεν υπάρχει αποτέλεσμα.

### ISSUE THREAD

**Issue by iliassachlos** [TouristGuideApp/Tourist-Guide-Frontend-App#12]
Δεν θα ηθελα να μην ενημερωνομαι και να περιμενω ασκοπα για αν τυχον δεν μπορει η ιστοσελιδα να μου διαθεσει φωτογραφιες για το μερος που αναζητησα. Θα καλυφτω με ενα μηνυμα που θα εμφανιζεται στην οθονη μου και θα με ενημερωνει για αυτο ακριβως το θεμα, οτι δεν υπαρχουν εικονες δηλαδη.

**Comment by gpapadopp** [comment]
Από το backend αυτό είναι έτοιμο. Σας απαντάω με status code 204 όταν δεν βρέθηκε καμία εικόνα (204 = no content), ενώ όταν υπάρχουν εικόνες, σας απαντάω με status code 200. Βρίσκεται στο branch (v3_us17), όπου μάλλον θα το κάνω merge με το integration.
Πλέον η μέθοδος του αν δεν υπάρχει εικόνα στη βάση, καλώ το flickr, δεν υπάρχει. Θα γεμίσουμε τη βάση μια φορά, με μια πολή που θέλετε, και θα παρουσιάσουμε αυτή.
